- name: Managing ACLs Using Ansible on Server 1
  hosts: stapp01
  become: true
  tasks:
    - name: Create an empty file
      ansible.builtin.file:
        path: /opt/itadmin/blog.txt
        state: touch
        mode: '0644'

    - name: Give ACL permission to group tony
      ansible.posix.acl:
        path: /opt/itadmin/blog.txt
        entity: tony
        etype: group
        permissions: r
        state: present


- name: Managing ACLs Using Ansible on App Server 2
  hosts: stapp02
  become: true
  tasks:
    - name: Create an empty file
      ansible.builtin.file:
        path: /opt/itadmin/story.txt
        state: touch
        mode: '0644'

    - name: Give ACL permission to user steve
      ansible.posix.acl:
        path: /opt/itadmin/story.txt
        entity: steve
        etype: user
        permissions: rw
        state: present


- name: Managing ACLs Using Ansible on App Server 3
  hosts: stapp03
  become: true
  tasks:
    - name: Create an empty file
      ansible.builtin.file:
        path: /opt/itadmin/media.txt
        state: touch
        mode: '0644'

    - name: Give ACL permission to group banner
      ansible.posix.acl:
        path: /opt/itadmin/media.txt
        entity: banner
        etype: group
        permissions: rw
        state: present
